server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/cinema/api/v1/movies/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/cinema/api/v1/users/**
        - id: showtime-service
          uri: lb://showtime-service
          predicates:
            - Path=/cinema/api/v1/showtimes/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/cinema/api/v1/bookings/**