spring:
  application:
    name: showtime-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9020
        instance:
          name: Showtime API Service
server:
  servlet:
    context-path: /cinema/api/v1
  port: 9070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS